dataset: "Irish"

###########################################################
#                      WHISPER SETTING                    #
###########################################################
model_size: "medium"               # three options: small, medium, large. small and medium are better than large
tokenizer_language: "english"     # there are different languages you can select
processor_language: "None"        # is same with tokenizer_language

###########################################################
#                      TRAINing SETTING                   #
###########################################################

per_device_train_batch_size: 16
gradient_accumulation_steps: 1
learning_rate: 0.00001            # 1e-5
warmup_steps: 500
max_steps: 15000
gradient_checkpointing: True
fp16: True
evaluation_strategy: "steps"
per_device_eval_batch_size: 8
predict_with_generate: True
generation_max_length: 225
save_steps: 1000
eval_steps: 1000
logging_steps: 25
load_best_model_at_end: True
metric_for_best_model: "wer"
greater_is_better: False

max_step: 4000

